apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: ssl-cert
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["/bin/sh"]
    args:
      - -c
      - |
        apt-get update &&
        apt-get install -y postgresql-client &&
        mkdir -p /root/.postgresql &&
        sleep 604800
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/root/.postgresql"
  restartPolicy: Always